name: met
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - pytorch=1.12.1
  - numpy=1.23.1
  - h5py=3.7.0
  - scipy==1.9.1
  - nibabel==2.3.0
  - monai==1.0.1
  - wandb==0.13.5